CREATE TABLE public.countyinfo2009(
	state_name varchar,
	county_code varchar,
	fips varchar,
	food_ins_rate varchar,
	number_food_ins_ppl varchar,
	low_threshold varchar,
	low_threshold_type varchar,
	high_threshold varchar,
	high_threshold_type varchar,
	perc_fi_less_low_thresh varchar,
	perc_fi_in_btwn_thresh varchar,
	perc_fi_greater_high_thresh varchar,
	weighted_annual_dollars varchar,
	cost_per_meal varchar,
	child_fi_rate varchar,
	num_food_ins_children varchar,
	perc_child_fi_hh_below_fpl varchar,
	perc_child_fi_hh_above_fpl varchar
);